# Generated by Django 2.1 on 2018-08-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_merge_20180816_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenterSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'water'), ('food', 'food')], max_length=100, verbose_name='Type')),
                ('received', models.IntegerField(default=0, verbose_name='Received')),
                ('total_received', models.IntegerField(default=0, verbose_name='Total Received')),
                ('no_allocated', models.IntegerField(default=0, verbose_name='Allocated')),
                ('total_allocated', models.IntegerField(default=0, verbose_name='Total allocated')),
            ],
        ),
        migrations.CreateModel(
            name='ReliefCampDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'water'), ('food', 'food')], max_length=100, verbose_name='Type')),
                ('no_request', models.IntegerField(default=0, verbose_name='Quantity')),
                ('total_request', models.IntegerField(default=0, verbose_name='Total Quantity')),
                ('no_allocated', models.IntegerField(default=0, verbose_name='Allocated')),
                ('total_allocated', models.IntegerField(default=0, verbose_name='Total allocated')),
                ('notes', models.CharField(max_length=100, verbose_name='Notes')),
                ('quantity_type', models.CharField(max_length=100, verbose_name='Quantity Type')),
                ('critical', models.BooleanField(default=False, verbose_name='Critical')),
            ],
        ),
        migrations.CreateModel(
            name='ReliefCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('district', models.CharField(max_length=500, verbose_name='District')),
                ('center_type', models.CharField(choices=[('Collection', 'Collection'), ('Camp', 'Camp')], max_length=100, verbose_name='Type')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone1', models.CharField(max_length=100, verbose_name='Phone1')),
                ('phone2', models.CharField(max_length=100, verbose_name='Phone2')),
                ('phone3', models.CharField(max_length=100, verbose_name='Phone3')),
                ('latlng', models.CharField(blank=True, max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ ')),
                ('latlng_accuracy', models.CharField(blank=True, max_length=100, verbose_name='GPS Accuracy - GPS കൃത്യത ')),
                ('no_men', models.IntegerField(default=0)),
                ('no_women', models.IntegerField(default=0)),
                ('no_infants', models.IntegerField(default=0)),
                ('no_children', models.IntegerField(default=0)),
                ('no_elder', models.IntegerField(default=0)),
                ('no_volunteers', models.IntegerField(default=0)),
                ('login_pin', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Shipped', 'Shipped'), ('Received', 'Received')], max_length=100, verbose_name='Status')),
                ('shipped', models.DateTimeField(auto_now_add=True, verbose_name='Shipped')),
                ('receieved', models.DateTimeField(auto_now_add=True, verbose_name='Received')),
                ('person', models.CharField(max_length=100, verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'water'), ('food', 'food')], max_length=100, verbose_name='Type')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SupplyTransaction')),
            ],
        ),
        migrations.AlterField(
            model_name='contributor',
            name='district',
            field=models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15),
        ),
        migrations.AlterField(
            model_name='districtcollection',
            name='district',
            field=models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15),
        ),
        migrations.AlterField(
            model_name='districtmanager',
            name='district',
            field=models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15),
        ),
        migrations.AlterField(
            model_name='districtneed',
            name='district',
            field=models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='district',
            field=models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15, verbose_name='Districts - ജില്ല'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='district',
            field=models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15),
        ),
        migrations.AddField(
            model_name='reliefcampdemand',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ReliefCenter'),
        ),
        migrations.AddField(
            model_name='collectioncentersupply',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ReliefCenter'),
        ),
    ]
